language: c++
script: cmake
os: linux
dist: trusty

matrix:
  include:
    - name: "clang - linux - debug"
    - env: CXX=clang++ BUILD_TYPE=Debug
      addons: &clang
        apt:
          packages: ["clang-8.0"]
          sources: &sources ["llvm-toolchain-trusty"]
    - name: "clang - linux - release"
      env: CXX=clang++ BUILD_TYPE=Release
      addons: *clang

script: sh ci/run.sh

notifications:
  email: false    
